apiVersion: v1
kind: Service
metadata:
  name: cyber-db-hs
spec:
  ports:
  - port: 5432
  clusterIP: None  # Headless : pas de répartition, on voit les pods directs
  selector:
    app: cyber-db