apiVersion: v1
kind: Service
metadata:
  name: cyber-world-entry
spec:
  selector:
    app: cyber-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer